/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 回転寿司オーダー API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetcher } from "./fetcher.ts";
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus = {
  ordered: "ordered",
  cooking: "cooking",
  delivered: "delivered",
} as const;

export interface Order {
  id: string;
  orderNumber: number;
  tableNumber: number;
  itemName: string;
  quantity: number;
  status: OrderStatus;
  createdAt: string;
  updatedAt: string;
}

export interface CreateOrderRequest {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  tableNumber: number;
  /** @minLength 1 */
  itemName: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  quantity: number;
}

export interface OrderListResponse {
  orders: Order[];
}

export interface OkResponse {
  ok: boolean;
}

export type GetApiOrdersParams = {
  status?: GetApiOrdersStatus;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  tableNumber?: number;
};

export type GetApiOrdersStatus =
  (typeof GetApiOrdersStatus)[keyof typeof GetApiOrdersStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiOrdersStatus = {
  ordered: "ordered",
  cooking: "cooking",
  delivered: "delivered",
} as const;

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const postApiOrders = (
  createOrderRequest: CreateOrderRequest,
  signal?: AbortSignal,
) => {
  return customFetcher<Order>({
    url: `/api/orders`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createOrderRequest,
    signal,
  });
};

export const getPostApiOrdersMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiOrders>>,
    TError,
    { data: CreateOrderRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiOrders>>,
  TError,
  { data: CreateOrderRequest },
  TContext
> => {
  const mutationKey = ["postApiOrders"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiOrders>>,
    { data: CreateOrderRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiOrders(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiOrdersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiOrders>>
>;
export type PostApiOrdersMutationBody = CreateOrderRequest;
export type PostApiOrdersMutationError = unknown;

export const usePostApiOrders = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiOrders>>,
    TError,
    { data: CreateOrderRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiOrders>>,
  TError,
  { data: CreateOrderRequest },
  TContext
> => {
  const mutationOptions = getPostApiOrdersMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getApiOrders = (
  params?: GetApiOrdersParams,
  signal?: AbortSignal,
) => {
  return customFetcher<OrderListResponse>({
    url: `/api/orders`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiOrdersQueryKey = (params?: GetApiOrdersParams) => {
  return [`/api/orders`, ...(params ? [params] : [])] as const;
};

export const getGetApiOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOrders>>,
  TError = unknown,
>(
  params?: GetApiOrdersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiOrders>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiOrdersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOrders>>> = ({
    signal,
  }) => getApiOrders(params, signal);

  return { queryKey, queryFn, ...queryOptions } as
    & UseQueryOptions<
      Awaited<ReturnType<typeof getApiOrders>>,
      TError,
      TData
    >
    & { queryKey: QueryKey };
};

export type GetApiOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOrders>>
>;
export type GetApiOrdersQueryError = unknown;

export function useGetApiOrders<
  TData = Awaited<ReturnType<typeof getApiOrders>>,
  TError = unknown,
>(
  params?: GetApiOrdersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiOrders>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiOrdersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiOrdersIdStart = (id: string) => {
  return customFetcher<OkResponse>({
    url: `/api/orders/${id}/start`,
    method: "PUT",
  });
};

export const getPutApiOrdersIdStartMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiOrdersIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiOrdersIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["putApiOrdersIdStart"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiOrdersIdStart>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return putApiOrdersIdStart(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiOrdersIdStartMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiOrdersIdStart>>
>;

export type PutApiOrdersIdStartMutationError = unknown;

export const usePutApiOrdersIdStart = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiOrdersIdStart>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiOrdersIdStart>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPutApiOrdersIdStartMutationOptions(options);

  return useMutation(mutationOptions);
};

export const putApiOrdersIdDeliver = (id: string) => {
  return customFetcher<OkResponse>({
    url: `/api/orders/${id}/deliver`,
    method: "PUT",
  });
};

export const getPutApiOrdersIdDeliverMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiOrdersIdDeliver>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiOrdersIdDeliver>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["putApiOrdersIdDeliver"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiOrdersIdDeliver>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return putApiOrdersIdDeliver(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiOrdersIdDeliverMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiOrdersIdDeliver>>
>;

export type PutApiOrdersIdDeliverMutationError = unknown;

export const usePutApiOrdersIdDeliver = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiOrdersIdDeliver>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiOrdersIdDeliver>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPutApiOrdersIdDeliverMutationOptions(options);

  return useMutation(mutationOptions);
};
